export type DepartmentView =
  | "executive"
  | "sales-head"
  | "sales-agent"
  | "rnd"
  | "finance";

export const DEPARTMENT_VIEW_OPTIONS: {
  id: DepartmentView;
  label: string;
  shortLabel: string;
  title: string;
  subtitle: string;
  roleLabel: string;
  icon: string;
}[] = [
  {
    id: "executive",
    label: "Executive overview",
    shortLabel: "Executive",
    title: "Executive overview",
    subtitle: "The complete COO and MD-level product-mix visibility platform.",
    roleLabel: "Commercial analyst",
    icon: "◆",
  },
  {
    id: "sales-head",
    label: "Sales Head",
    shortLabel: "Sales Head",
    title: "Commercial growth command",
    subtitle: "Portfolio, territory and recommendation signals for directing growth and recovery.",
    roleLabel: "Sales Head · Commercial Growth",
    icon: "↗",
  },
  {
    id: "sales-agent",
    label: "Sales Agent",
    shortLabel: "Sales Agent",
    title: "Territory action workspace",
    subtitle: "A focused SKU queue for replenishment, whitespace trials and outcome follow-up.",
    roleLabel: "Sales Agent · Field Action",
    icon: "◎",
  },
  {
    id: "rnd",
    label: "R&D",
    shortLabel: "R&D",
    title: "Product signal laboratory",
    subtitle: "Product movement, return risk, trial potential and design-to-cost evidence.",
    roleLabel: "R&D · Product Development",
    icon: "⌬",
  },
  {
    id: "finance",
    label: "Finance",
    shortLabel: "Finance",
    title: "Revenue and valuation control",
    subtitle: "Revenue, return leakage, stock exposure and profitability readiness.",
    roleLabel: "Finance · Commercial Control",
    icon: "▤",
  },
];

/*
 * Every field already visible on an Executive page is deliberately owned by at
 * least one departmental view. The role components consume the same dashboard
 * payload; this map is the reviewable field-conservation contract.
 */
export const EXECUTIVE_VISIBLE_FIELDS = [
  "activeProducts",
  "pricedProducts",
  "describedProducts",
  "categorizedProducts",
  "salesUnitProducts",
  "grossMarginProducts",
  "activeProfiles",
  "learningStates",
  "activeModelVersion",
  "valuationRows",
  "stockBearingProducts",
  "salesCustomers",
  "geocodedSalesCustomers",
  "geoCoveragePct",
  "invoiceLines",
  "invoices",
  "recommendations",
  "recommendationLines",
  "whitespaceTrialLines",
  "graduatedLines",
  "recommendedValue",
  "feedbackRecords",
  "soldProducts",
  "activeMarketCustomers",
  "netSales",
  "grossSales",
  "returnsValue",
  "returnRatePct",
  "netQuantity",
  "salesDateFrom",
  "salesDateTo",
  "salesRegions",
  "product_id",
  "product_name",
  "category",
  "valuation_area_count",
  "valuation_class",
  "price_control",
  "selected_cost",
  "total_stock",
  "sales_line_count",
  "invoice_count",
  "buyer_count",
  "sales_region_count",
  "net_quantity",
  "gross_quantity",
  "return_quantity",
  "net_sales_value",
  "gross_sales_value",
  "returns_value",
  "first_sale_date",
  "last_sale_date",
  "observed_unit_price",
  "return_rate_pct",
  "sales_trend_pct",
  "buyer_penetration_pct",
  "whitespace_customers",
  "familiar_profile_count",
  "whitespace_trial_profile_count",
  "graduated_profile_count",
  "month",
  "monthly_gross_sales",
  "monthly_returns_value",
  "monthly_net_sales",
  "region_label",
  "regional_invoice_lines",
  "regional_invoices",
  "regional_active_buyers",
  "regional_sold_products",
  "regional_geocoded_buyers",
  "regional_net_quantity",
  "regional_net_sales",
  "regional_gross_sales",
  "regional_returns_value",
  "regional_return_rate_pct",
  "recommendation_acceptance",
  "recommendation_target",
  "recommendation_actual",
  "recommendation_outcome",
  "recommendation_latency",
  "non_acceptance_reason",
] as const;

export const DEPARTMENT_FIELD_OWNERSHIP: Record<
  Exclude<DepartmentView, "executive">,
  readonly string[]
> = {
  "sales-head": [
    "soldProducts",
    "activeProducts",
    "activeMarketCustomers",
    "salesCustomers",
    "geocodedSalesCustomers",
    "geoCoveragePct",
    "invoices",
    "invoiceLines",
    "netSales",
    "grossSales",
    "returnsValue",
    "returnRatePct",
    "recommendations",
    "recommendationLines",
    "whitespaceTrialLines",
    "graduatedLines",
    "recommendedValue",
    "feedbackRecords",
    "salesRegions",
    "salesDateFrom",
    "salesDateTo",
    "product_id",
    "product_name",
    "category",
    "sales_line_count",
    "invoice_count",
    "buyer_count",
    "sales_region_count",
    "net_quantity",
    "return_quantity",
    "net_sales_value",
    "returns_value",
    "first_sale_date",
    "last_sale_date",
    "sales_trend_pct",
    "buyer_penetration_pct",
    "whitespace_customers",
    "total_stock",
    "observed_unit_price",
    "familiar_profile_count",
    "whitespace_trial_profile_count",
    "graduated_profile_count",
    "region_label",
    "regional_invoice_lines",
    "regional_invoices",
    "regional_active_buyers",
    "regional_sold_products",
    "regional_geocoded_buyers",
    "regional_net_quantity",
    "regional_net_sales",
    "regional_returns_value",
    "regional_return_rate_pct",
    "recommendation_acceptance",
    "recommendation_target",
    "recommendation_actual",
    "recommendation_outcome",
    "recommendation_latency",
  ],
  "sales-agent": [
    "salesDateFrom",
    "salesDateTo",
    "recommendations",
    "recommendationLines",
    "whitespaceTrialLines",
    "feedbackRecords",
    "product_id",
    "product_name",
    "category",
    "invoice_count",
    "buyer_count",
    "net_quantity",
    "return_quantity",
    "net_sales_value",
    "returns_value",
    "last_sale_date",
    "observed_unit_price",
    "return_rate_pct",
    "sales_trend_pct",
    "buyer_penetration_pct",
    "whitespace_customers",
    "familiar_profile_count",
    "whitespace_trial_profile_count",
    "graduated_profile_count",
    "total_stock",
    "recommendation_acceptance",
    "recommendation_target",
    "recommendation_actual",
    "recommendation_outcome",
    "recommendation_latency",
    "non_acceptance_reason",
  ],
  rnd: [
    "activeProducts",
    "describedProducts",
    "categorizedProducts",
    "salesUnitProducts",
    "activeProfiles",
    "learningStates",
    "activeModelVersion",
    "product_id",
    "product_name",
    "category",
    "sales_region_count",
    "net_quantity",
    "gross_quantity",
    "return_quantity",
    "net_sales_value",
    "returns_value",
    "first_sale_date",
    "last_sale_date",
    "observed_unit_price",
    "return_rate_pct",
    "sales_trend_pct",
    "buyer_count",
    "buyer_penetration_pct",
    "whitespace_customers",
    "familiar_profile_count",
    "whitespace_trial_profile_count",
    "graduated_profile_count",
    "total_stock",
    "selected_cost",
    "valuation_area_count",
    "valuation_class",
    "price_control",
    "non_acceptance_reason",
    "recommendation_outcome",
  ],
  finance: [
    "pricedProducts",
    "grossMarginProducts",
    "valuationRows",
    "stockBearingProducts",
    "invoiceLines",
    "invoices",
    "netSales",
    "grossSales",
    "returnsValue",
    "returnRatePct",
    "netQuantity",
    "recommendedValue",
    "recommendations",
    "recommendationLines",
    "product_id",
    "product_name",
    "category",
    "sales_line_count",
    "invoice_count",
    "net_quantity",
    "gross_quantity",
    "return_quantity",
    "net_sales_value",
    "gross_sales_value",
    "returns_value",
    "first_sale_date",
    "last_sale_date",
    "observed_unit_price",
    "return_rate_pct",
    "sales_trend_pct",
    "total_stock",
    "selected_cost",
    "valuation_area_count",
    "valuation_class",
    "price_control",
    "month",
    "monthly_gross_sales",
    "monthly_returns_value",
    "monthly_net_sales",
    "region_label",
    "regional_invoice_lines",
    "regional_invoices",
    "regional_net_quantity",
    "regional_net_sales",
    "regional_gross_sales",
    "regional_returns_value",
    "regional_return_rate_pct",
    "recommendation_acceptance",
  ],
};

